version: "3.3"
services:
  db:
    image: "postgres"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "post_app"

  nodejs-server:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: node-api
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/post_app?schema=public"

  react-ui:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/post-app/frontend
      - /usr/src/post-app/frontend/node_modules
